### ISSUE TITLE
check performance

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-demo-bsm-search#21]
The `reana-demo-bsm-search` example, tagged 1.0.0, is finishing in:

- about 9 minutes on PROD, using REANA version 0.6.0 plus:

```console
$ reana-client status -w bsm
NAME   RUN_NUMBER   CREATED               STARTED               ENDED                 STATUS     PROGRESS
bsm    1            2020-09-07T09:20:51   2020-09-07T09:21:04   2020-09-07T09:30:44   finished   67/65
```

- about 47 minutes on QA, using REANA 0.7.0-alpha.2:

```console
$ reana-client status -w bsm
NAME   RUN_NUMBER   CREATED               STARTED               ENDED                 STATUS     PROGRESS
bsm    3            2020-09-07T08:57:30   2020-09-07T08:57:31   2020-09-07T09:44:53   finished   67/65
```

- about 7 minutes on an old E5-2620 box, using about two-month old REANA `master`sources (e.g. `r-w-e-yadage@64fb637`), deployed via Kind:

```console
$ reana-client status -w bsm
NAME   RUN_NUMBER   CREATED               STARTED               ENDED                 STATUS     PROGRESS
bsm    1            2020-09-07T09:58:56   2020-09-07T09:59:07   2020-09-07T10:06:19   finished   67/65
```

- about 30 minutes on a modern laptop (i7-9750H), using latest REANA `master` sources, deployed via Kind:

```console
$ reana-client status -w bsm
NAME   RUN_NUMBER   CREATED               STARTED               ENDED                 STATUS    PROGRESS
bsm    1            2020-09-07T11:49:51   2020-09-07T11:50:40   2020-09-07T12:20:21   finished  67/65
```

In all cases, the BSM example to run was the same (the tagged `1.0.0` version), and all deployments were pre-loaded with necessary Docker images so that there is no docker image pulling time obstructing the picture. The only thing that changes is the hardware and the REANA version. And note that hardware does not play a role, since old machine with old REANA was faster than a new machine with new REANA.

It therefore seems that we have introduced a performance problem sometime in July-August this year. The difference is very visible for this demo workflow. It could be related to changes in `r-w-e-yadage` (py38? options?) or to changes in the REANA infrastructure itself (job monitoring? job controller? workflow execution?).

We should profile the BSM run in order to find the root cause and address the problem. We can start bisecting from O(60) days-old `master` version that is known to work fast.

**Comment by mvidalgarcia** [comment]
Some news on BSM slowness, all components in master and `r-w-e-yadage` in [`9bf44e1`](https://github.com/reanahub/reana-workflow-engine-yadage/commit/9bf44e1ddf1dd58de1319c277ccbf77e23c71015). Finished in 9min.
